export const certificates = [
  { image: 'freecodecamp-data-analysis-with-python.jpg', title: 'Data Analysis with Python', issuer: 'freeCodeCamp' },
  { image: 'freecodecamp-machine-learning-with-python.jpg', title: 'Machine Learning with Python', issuer: 'freeCodeCamp' },
  { image: 'freecodecamp-responsive-web-design.jpg', title: 'Responsive Web Design', issuer: 'freeCodeCamp' },
  { image: 'google-cloud-classify-images-with-tensorflow.jpg', title: 'Classify Images with TensorFlow on Google Cloud', issuer: 'Google Cloud' },
  { image: 'google-cloud-generative-ai-fundamentals.jpg', title: 'Generative AI Fundamentals', issuer: 'Google Cloud' },
  { image: 'google-cloud-transformer-models-and-bert.jpg', title: 'Transformer Models and BERT Model', issuer: 'Google Cloud' },
  { image: 'google-cloud-attention-mechanism.jpg', title: 'Attention Mechanism', issuer: 'Google Cloud' },
  { image: 'google-cloud-baseline-data-ml-ai.jpg', title: 'Baseline: Data, ML, AI', issuer: 'Google Cloud' },
  { image: 'google-cloud-encoder-decoder-architecture.jpg', title: 'Encoder-Decoder Architecture', issuer: 'Google Cloud' },
  { image: 'google-cloud-gemini-for-application-developers.jpg', title: 'Gemini for Application Developers', issuer: 'Google Cloud' },
  { image: 'google-cloud-gemini-for-data-scientists-and-analysts.jpg', title: 'Gemini for Data Scientists and Analysts', issuer: 'Google Cloud' },
  { image: 'google-cloud-innovating-with-generative-ai.jpg', title: 'Innovating with Google Cloud Artificial Intelligence', issuer: 'Google Cloud' },
  { image: 'google-cloud-intro-to-ml-language-processing.jpg', title: 'Intro to ML: Language Processing', issuer: 'Google Cloud' },
  { image: 'google-cloud-intro-to-ml-image-processing.jpg', title: 'Intro to ML: Image Processing', issuer: 'Google Cloud' },
  { image: 'google-cloud-introduction-to-image-generation.jpg', title: 'Introduction to Image Generation', issuer: 'Google Cloud' },
  { image: 'google-cloud-introduction-to-large-language-models.jpg', title: 'Introduction to Large Language Models', issuer: 'Google Cloud' },
  { image: 'google-cloud-introduction-to-responsible-ai.jpg', title: 'Introduction to Responsible AI', issuer: 'Google Cloud' },
  { image: 'aws-foundations-of-prompt-engineering.jpg', title: 'Foundations of Prompt Engineering', issuer: 'AWS Training and Certification' },
  { image: 'aws-introduction-to-generative-ai-art-of-the-possible.jpg', title: 'Introduction to Generative AI: Art of the Possible', issuer: 'AWS Training and Certification' },
  { image: 'coursera-google-cloud-introduction-to-generative-ai.jpg', title: 'Introduction to Generative AI', issuer: 'Google Cloud via Coursera' },
]
